# Generated by Django 5.0.1 on 2024-01-31 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccountModel",
            new_name="Account",
        ),
        migrations.RenameModel(
            old_name="ReceiptModel",
            new_name="Receipt",
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
